# Generated by Django 3.1 on 2020-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True, verbose_name='ID пользователя')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя пользователя')),
                ('today_cash', models.FloatField(blank=True, default=0, verbose_name='Вложения сегодня')),
                ('luck_point', models.IntegerField(blank=True, default=0, verbose_name='Кол-во мест выигрыша')),
                ('state_now', models.CharField(blank=True, max_length=200, verbose_name='Текущее состояние пользователя')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
