# Generated by Django 3.0.3 on 2020-09-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minigame_points',
            field=models.IntegerField(default=0, verbose_name='Очки за мини-игры'),
        ),
    ]
