# Generated by Django 3.0.3 on 2020-09-14 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200914_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minigame_counter_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведенных игр'),
        ),
    ]
