# Generated by Django 3.0.3 on 2020-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200914_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minigame_number',
            field=models.CharField(default='', max_length=200, verbose_name='Число пользователя'),
        ),
    ]
