# Generated by Django 3.0.3 on 2020-09-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200920_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minigame_random_list',
            field=models.CharField(default='', max_length=200, verbose_name='Число пользователя'),
        ),
    ]
