# Generated by Django 3.0.3 on 2020-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_user_minigame_random_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minigame_number',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Число пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='minigame_random_list',
            field=models.CharField(default='', max_length=200, verbose_name='Рандомное данное число'),
        ),
    ]
