# Generated by Django 3.0.3 on 2020-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20200920_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='minigame_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Число пользователя'),
        ),
    ]
