# Generated by Django 3.1.1 on 2020-09-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='luck_point',
        ),
    ]
