# Generated by Django 3.1.1 on 2020-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_user_luck_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid_for_minigame',
            field=models.BooleanField(default=False),
        ),
    ]
